// ============================================================
// 固定費の合計 (機能122) と 定期支出の自動検出・登録提案 (機能081)
//
// 122 は「繰り返し入力(recurring_rules)に登録済みのもの」だけを集計する。
//     推測ではなく登録内容そのものなので、数字を断定して出せる。
// 081 は過去の記録からの**推測**。誤検出で登録が勝手に増えるのが最悪なので、
//     - ここでは候補を出すだけで、登録は必ず画面側のユーザー操作を経る
//     - すでに登録済み(停止中も含む)の店は候補から外す
//     - 「いらない」と言われた候補は端末に覚えて二度と出さない
//     という三段構えにしてある。
// ============================================================

import { useSyncExternalStore } from 'react'
import type { Transaction } from './types'
import { isAutoGenerated } from './types'
import type { Recurrence, RecurrenceKind } from './recurrence'
import type { RecurringRule, RecurringRuleInput } from './recurringRules'
import { addDays } from './reportBuckets'

// ---------- 122: 登録済み固定費の集計 ----------

/** 年の週数。52週ちょうどではなく 365÷7 で換算する(毎週の年額を過小に見せないため) */
const WEEKS_PER_YEAR = 365 / 7

export interface FixedCostItem {
  id: string
  title: string
  /** 支払い総額ベースの月額換算 */
  monthly: number
  /** 自分の実質負担ベースの月額換算(レポートの他の数字と揃える) */
  monthlyOwn: number
  annual: number
  annualOwn: number
  kind: RecurrenceKind
}

export interface FixedCostSummary {
  items: FixedCostItem[]
  monthlyTotal: number
  monthlyOwnTotal: number
  annualTotal: number
  annualOwnTotal: number
  /** 停止中で集計から外した件数(0 でないときは画面に添える) */
  pausedCount: number
}

/** 1件の年額換算。(純粋関数) 毎月=12倍 / 毎週=365÷7倍 / 毎年=そのまま */
export function annualOfRule(amount: number, kind: RecurrenceKind): number {
  if (kind === 'monthly') return amount * 12
  if (kind === 'weekly') return amount * WEEKS_PER_YEAR
  return amount
}

/**
 * 登録済みの繰り返し入力から固定費を束ねる。(純粋関数)
 * 停止中のルールは「毎月出ていくもの」ではないので合計から外す。
 */
export function fixedCostSummary(rules: readonly RecurringRule[]): FixedCostSummary {
  const active = rules.filter((r) => r.active)
  const items: FixedCostItem[] = active.map((r) => {
    const own = Math.max(0, r.amount - r.partnerAmount)
    const annual = annualOfRule(r.amount, r.recurrence.kind)
    const annualOwn = annualOfRule(own, r.recurrence.kind)
    return {
      id: r.id,
      title: r.title,
      monthly: Math.round(annual / 12),
      monthlyOwn: Math.round(annualOwn / 12),
      annual: Math.round(annual),
      annualOwn: Math.round(annualOwn),
      kind: r.recurrence.kind,
    }
  })
  // 金額の大きい順(同額は名前順)。何が効いているかを上から読めるようにする
  items.sort((a, b) => b.monthly - a.monthly || (a.title < b.title ? -1 : a.title > b.title ? 1 : 0))

  return {
    items,
    monthlyTotal: items.reduce((s, i) => s + i.monthly, 0),
    monthlyOwnTotal: items.reduce((s, i) => s + i.monthlyOwn, 0),
    annualTotal: items.reduce((s, i) => s + i.annual, 0),
    annualOwnTotal: items.reduce((s, i) => s + i.annualOwn, 0),
    pausedCount: rules.length - active.length,
  }
}

// ---------- 081: 定期支出の検出 ----------

/** 候補と認めるのに必要な最低回数。2回では「たまたま2回買った」と区別できない */
export const MIN_OCCURRENCES = 3
/** 遡る日数。毎年の支払いも3回(=2年ぶんの間隔)拾えるよう3年ぶんを見る */
export const LOOKBACK_DAYS = 1100
/** 金額のばらつきの許容(中央値に対する比率と、最低限の絶対値) */
export const AMOUNT_TOLERANCE_RATIO = 0.1
export const AMOUNT_TOLERANCE_MIN = 100
/** 「まだ続いている」とみなす猶予。周期の1.5倍+7日を過ぎたら解約済みとみて出さない */
export const STALE_FACTOR = 1.5
export const STALE_GRACE_DAYS = 7

interface PeriodSpec {
  kind: RecurrenceKind
  min: number
  max: number
  /** 各間隔が中央値からどれだけ離れてよいか(日) */
  tolerance: number
}

/**
 * 周期の判定表。月次は「毎月同じ日」でも 28〜31 日のぶれが出るので幅を持たせ、
 * 年次はうるう年と支払日の前後で 350〜380 日を許す。
 */
const PERIOD_SPECS: PeriodSpec[] = [
  { kind: 'weekly', min: 6, max: 8, tolerance: 2 },
  { kind: 'monthly', min: 27, max: 33, tolerance: 4 },
  { kind: 'yearly', min: 350, max: 380, tolerance: 20 },
]

export interface RecurringCandidate {
  /** 除外リストの照合に使う正規化キー(店名ベース) */
  key: string
  /** 表示用の店名(いちばん新しい記録の表記) */
  store: string
  occurrences: number
  dates: string[]
  lastDate: string
  medianAmount: number
  medianPartnerAmount: number
  medianIntervalDays: number
  recurrence: Recurrence
  category: string | null
  /** 並び順と「毎月いくら」の目安に使う */
  monthlyEquivalent: number
}

/** 店名の表記ゆれを寄せる。(純粋関数) 空白と大文字小文字だけを吸収する控えめな正規化 */
export function normalizeStoreKey(store: string): string {
  return store
    .trim()
    .toLowerCase()
    .replace(/[\s　]+/g, '')
}

function median(values: readonly number[]): number {
  const sorted = [...values].sort((a, b) => a - b)
  const mid = Math.floor(sorted.length / 2)
  return sorted.length % 2 === 1 ? sorted[mid] : Math.round((sorted[mid - 1] + sorted[mid]) / 2)
}

/** 日数の差(a→b)。夏時間の無い日本でも安全側に倒して UTC で引く */
function daysBetween(a: string, b: string): number {
  const [y1, m1, d1] = a.split('-').map(Number)
  const [y2, m2, d2] = b.split('-').map(Number)
  return Math.round((Date.UTC(y2, m2 - 1, d2) - Date.UTC(y1, m1 - 1, d1)) / 86_400_000)
}

/** 最頻値。同数なら小さい方に寄せて、結果が入力順で変わらないようにする */
function mode(values: readonly number[]): number {
  const counts = new Map<number, number>()
  for (const v of values) counts.set(v, (counts.get(v) ?? 0) + 1)
  return [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0] - b[0])[0][0]
}

function modeOfCategory(values: readonly (string | null)[]): string | null {
  const counts = new Map<string, number>()
  for (const v of values) {
    if (v === null) continue
    counts.set(v, (counts.get(v) ?? 0) + 1)
  }
  if (counts.size === 0) return null
  return [...counts.entries()].sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1))[0][0]
}

interface Occurrence {
  date: string
  amount: number
  partner: number
  category: string | null
  store: string
}

/**
 * 過去の記録から「これは定期では?」という候補を挙げる。(純粋関数)
 *
 * 条件(すべて満たしたものだけを候補にする):
 *   1. 同じ店名(正規化後)で {@link MIN_OCCURRENCES} 回以上
 *   2. 連続する間隔の中央値が、毎週 / 毎月 / 毎年 のいずれかの幅に入る
 *   3. **すべての**間隔が中央値 ± 許容日数に収まる(ばらつく買い物を弾く)
 *   4. 金額が中央値 ± max(10%, 100円) に収まる
 *   5. 最後の記録が新しい(周期の1.5倍+7日以内)= まだ続いている
 *   6. 繰り返し入力に同じ店・同じ名前の登録が無い(停止中の登録も再提案しない)
 *   7. ユーザーが「いらない」と言った候補でない
 *
 * 自動生成された記録(source='recurring')は最初から除く。登録済みルールが
 * 作った行を材料にして同じルールを再提案しては本末転倒なため。
 */
export function detectRecurringCandidates(
  txs: readonly Transaction[],
  rules: readonly Pick<RecurringRule, 'store' | 'title'>[],
  today: string,
  dismissedKeys: readonly string[] = []
): RecurringCandidate[] {
  const since = addDays(today, -LOOKBACK_DAYS)
  const registered = new Set<string>()
  for (const r of rules) {
    const store = normalizeStoreKey(r.store)
    if (store !== '') registered.add(store)
    const title = normalizeStoreKey(r.title)
    if (title !== '') registered.add(title)
  }
  const dismissed = new Set(dismissedKeys)

  // 店名ごと・日付ごとにまとめる(同じ日の複数件は1回の支払いとして合算)
  const groups = new Map<string, Map<string, Occurrence>>()
  for (const t of txs) {
    if (t.type !== 'expense') continue
    if (isAutoGenerated(t)) continue
    const store = t.store.trim()
    if (store === '') continue // 店名が無いと同じ支払いだと言い切れない
    if (t.date < since || t.date > today) continue
    const key = normalizeStoreKey(store)
    if (key === '' || registered.has(key) || dismissed.has(key)) continue
    const byDate = groups.get(key) ?? new Map<string, Occurrence>()
    const cur = byDate.get(t.date)
    if (cur) {
      cur.amount += t.amount
      cur.partner += t.partner_amount
    } else {
      byDate.set(t.date, {
        date: t.date,
        amount: t.amount,
        partner: t.partner_amount,
        category: t.category,
        store,
      })
    }
    groups.set(key, byDate)
  }

  const out: RecurringCandidate[] = []
  for (const [key, byDate] of groups) {
    const occurrences = [...byDate.values()].sort((a, b) => (a.date < b.date ? -1 : 1))
    if (occurrences.length < MIN_OCCURRENCES) continue

    const intervals: number[] = []
    for (let i = 1; i < occurrences.length; i++) {
      intervals.push(daysBetween(occurrences[i - 1].date, occurrences[i].date))
    }
    if (intervals.length < MIN_OCCURRENCES - 1) continue

    const medianInterval = median(intervals)
    const spec = PERIOD_SPECS.find((s) => medianInterval >= s.min && medianInterval <= s.max)
    if (!spec) continue
    if (intervals.some((d) => Math.abs(d - medianInterval) > spec.tolerance)) continue

    const amounts = occurrences.map((o) => o.amount)
    const medianAmount = median(amounts)
    const tolerance = Math.max(medianAmount * AMOUNT_TOLERANCE_RATIO, AMOUNT_TOLERANCE_MIN)
    if (amounts.some((a) => Math.abs(a - medianAmount) > tolerance)) continue

    const last = occurrences[occurrences.length - 1]
    if (daysBetween(last.date, today) > medianInterval * STALE_FACTOR + STALE_GRACE_DAYS) continue

    const days = occurrences.map((o) => Number(o.date.slice(8, 10)))
    const weekdays = occurrences.map((o) => {
      const [y, m, d] = o.date.split('-').map(Number)
      return new Date(y, m - 1, d).getDay()
    })
    const recurrence: Recurrence =
      spec.kind === 'weekly'
        ? { kind: 'weekly', dayOfMonth: null, weekday: mode(weekdays), monthOfYear: null }
        : spec.kind === 'monthly'
          ? { kind: 'monthly', dayOfMonth: mode(days), weekday: null, monthOfYear: null }
          : {
              kind: 'yearly',
              // 毎年は回数が少ないので最頻値ではなく直近の実績日をそのまま採る
              dayOfMonth: Number(last.date.slice(8, 10)),
              weekday: null,
              monthOfYear: Number(last.date.slice(5, 7)),
            }

    out.push({
      key,
      store: last.store,
      occurrences: occurrences.length,
      dates: occurrences.map((o) => o.date),
      lastDate: last.date,
      medianAmount,
      medianPartnerAmount: median(occurrences.map((o) => o.partner)),
      medianIntervalDays: medianInterval,
      recurrence,
      category: modeOfCategory(occurrences.map((o) => o.category)),
      monthlyEquivalent: Math.round(annualOfRule(medianAmount, spec.kind) / 12),
    })
  }

  // 月額換算の大きい順(同額はキー順)。効きの大きいものから確認できるように
  return out.sort(
    (a, b) => b.monthlyEquivalent - a.monthlyEquivalent || (a.key < b.key ? -1 : a.key > b.key ? 1 : 0)
  )
}

/**
 * 候補から繰り返し入力の登録内容を組み立てる。(純粋関数)
 *
 * 開始日を**翌日**にしているのが要点。開始日を今日以前にすると、
 * すでに手入力してある過去の支払いぶんが自動生成で二重に積まれてしまう。
 */
export function buildRuleInputFromCandidate(
  candidate: RecurringCandidate,
  today: string
): RecurringRuleInput {
  return {
    title: candidate.store,
    recurrence: candidate.recurrence,
    amount: candidate.medianAmount,
    category: candidate.category,
    store: candidate.store,
    memo: '',
    partnerAmount: Math.min(candidate.medianPartnerAmount, candidate.medianAmount),
    startDate: addDays(today, 1),
    active: true,
  }
}

// ---------- 「この提案はいらない」の記憶(端末ごと) ----------

const DISMISS_KEY = 'kakeibo.recurringSuggestDismissed'

function loadDismissed(): string[] {
  try {
    const raw = localStorage.getItem(DISMISS_KEY)
    if (!raw) return []
    const parsed: unknown = JSON.parse(raw)
    return Array.isArray(parsed) ? parsed.filter((v): v is string => typeof v === 'string') : []
  } catch {
    return []
  }
}

let dismissedKeys: string[] = loadDismissed()
const listeners = new Set<() => void>()

export function getDismissedSuggestions(): string[] {
  return dismissedKeys
}

export function dismissSuggestion(key: string): void {
  if (dismissedKeys.includes(key)) return
  dismissedKeys = [...dismissedKeys, key]
  try {
    localStorage.setItem(DISMISS_KEY, JSON.stringify(dismissedKeys))
  } catch {
    // 保存できなくてもこのセッションでは消えたままになる
  }
  for (const l of listeners) l()
}

/** 非表示にした提案をすべて元に戻す(誤って消したときの逃げ道) */
export function clearDismissedSuggestions(): void {
  dismissedKeys = []
  try {
    localStorage.removeItem(DISMISS_KEY)
  } catch {
    // 消せなくてもこのセッションでは反映される
  }
  for (const l of listeners) l()
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener)
  return () => listeners.delete(listener)
}

export function useDismissedSuggestions(): string[] {
  return useSyncExternalStore(subscribe, getDismissedSuggestions, getDismissedSuggestions)
}
