export type TransactionType = 'expense' | 'partner_deposit'

/**
 * 支出に対する感情スタンプ (機能219 + 143)。
 * 入力時に押すスタンプ(219)と、あとからまとめて仕分ける画面(143)は
 * 同じ1列を読み書きする。二重に持たせない。
 */
export type Satisfaction = 'good' | 'neutral' | 'regret'

export const SATISFACTION_VALUES: readonly Satisfaction[] = ['good', 'neutral', 'regret']

export interface Transaction {
  id: string
  date: string // YYYY-MM-DD
  type: TransactionType
  amount: number // 支払い総額(円)。partner_deposit の場合は預かり額
  category: string | null
  memo: string
  store: string // お店(店名)。任意。支出でのみ使用(既定は空文字)
  partner_amount: number // 支出のうち彼女の負担分(円)。彼女残高から差し引かれる
  created_at: string
  // 'recurring' なら繰り返し入力が自動生成した行。手入力の行には無い(列自体が
  // 無い環境もあるので任意)。編集・削除の扱いは手入力の行と同じ。
  source?: string | null
  // 感情スタンプ。未設定(null)を許す。migration-satisfaction.sql 未実行の環境では
  // 列自体が存在しないので任意にしてある(その間はアプリ側で機能を静かに止める)。
  satisfaction?: Satisfaction | null
}

/** 繰り返し入力によって自動生成された行か */
export function isAutoGenerated(t: Transaction): boolean {
  return t.source === 'recurring'
}

/** 未知の値(古いキャッシュ・手で入れた行)を弾いて感情スタンプとして読む */
export function isSatisfaction(value: unknown): value is Satisfaction {
  return typeof value === 'string' && (SATISFACTION_VALUES as readonly string[]).includes(value)
}

/** 感情スタンプ。未設定・未知の値はすべて null に寄せる */
export function satisfactionOf(t: Transaction): Satisfaction | null {
  return isSatisfaction(t.satisfaction) ? t.satisfaction : null
}

// 自分の実質支出(彼女の負担分を除く)
export function ownAmount(t: Transaction): number {
  return t.type === 'expense' ? t.amount - t.partner_amount : 0
}
