/**
 * 取引の種別。
 *
 * expense / partner_deposit は最初からあるもの。
 * partner_refund / partner_adjust は預かり金の「返金」「手動調整」(機能012)で足した。
 * どちらも彼女の預かり残高だけを動かし、自分の支出の集計(report.ts)には一切入らない
 * (ownAmount が expense 以外を 0 として扱うため)。
 *
 * 「現金で受け取った」に専用の型を作っていないのは、残高への効果も意味も
 * 既存の partner_deposit(彼女→私へお金が動いた)とまったく同じだからで、
 * 型を増やすほど履歴・通知・共有ページの分岐が増えて壊れる面が広がるため。
 */
export type TransactionType = 'expense' | 'partner_deposit' | 'partner_refund' | 'partner_adjust'

/** 彼女の預かり残高だけを動かす種別(支出ではないもの) */
export const PARTNER_LEDGER_TYPES: readonly TransactionType[] = [
  'partner_deposit',
  'partner_refund',
  'partner_adjust',
]

export function isPartnerLedgerType(type: TransactionType): boolean {
  return (PARTNER_LEDGER_TYPES as readonly string[]).includes(type)
}

/**
 * 支出に対する感情スタンプ (機能219 + 143)。
 * 入力時に押すスタンプ(219)と、あとからまとめて仕分ける画面(143)は
 * 同じ1列を読み書きする。二重に持たせない。
 */
export type Satisfaction = 'good' | 'neutral' | 'regret'

export const SATISFACTION_VALUES: readonly Satisfaction[] = ['good', 'neutral', 'regret']

export interface Transaction {
  id: string
  date: string // YYYY-MM-DD
  type: TransactionType
  amount: number // 支払い総額(円)。partner_deposit の場合は預かり額
  category: string | null
  memo: string
  store: string // お店(店名)。任意。支出でのみ使用(既定は空文字)
  partner_amount: number // 支出のうち彼女の負担分(円)。彼女残高から差し引かれる
  created_at: string
  // 'recurring' なら繰り返し入力が自動生成した行。手入力の行には無い(列自体が
  // 無い環境もあるので任意)。編集・削除の扱いは手入力の行と同じ。
  source?: string | null
  // 感情スタンプ。未設定(null)を許す。migration-satisfaction.sql 未実行の環境では
  // 列自体が存在しないので任意にしてある(その間はアプリ側で機能を静かに止める)。
  satisfaction?: Satisfaction | null
  // 支払い総額のうち「彼女が実際に財布から出した額」(機能018)。
  // 既定は 0 = 自分が全額払った(これまでの前提)。列が無い環境では undefined。
  // 残高への影響は partner_paid − partner_amount(partnerBalance.ts)。
  partner_paid?: number | null
  // タグ (機能088)。カテゴリと直交する軸。列が無い環境では undefined。
  tags?: string[] | null
  // 1件を複数カテゴリに分割したときの束ねID (機能096)。
  // 分割は「1行 = 1カテゴリ」の独立した行として保存し、この列だけで束ねる。
  split_group?: string | null
  // おごり・値引き (favors.ts)。「実際に払った額より本来の値段が高かった」回。
  // 列が無い環境では undefined。**amount には一切足さない** —
  // 払っていないお金を支出の集計に混ぜないため(本来の値段は amount + favor_amount)。
  favor_amount?: number | null
  favor_kind?: string | null // 'treat'(おごり) / 'discount'(値引き) / null
  favor_from?: string | null // おごってくれた人。おごりのときだけ入る
}

/** 彼女が実際に払った額。列が無い/未設定は 0(= 自分が全額払った) */
export function partnerPaid(t: { partner_paid?: number | null }): number {
  return typeof t.partner_paid === 'number' && Number.isFinite(t.partner_paid) ? t.partner_paid : 0
}

/** タグ。列が無い/未設定は空配列 */
export function tagsOf(t: { tags?: string[] | null }): string[] {
  return Array.isArray(t.tags) ? t.tags.filter((s): s is string => typeof s === 'string') : []
}

/** 繰り返し入力によって自動生成された行か */
export function isAutoGenerated(t: Transaction): boolean {
  return t.source === 'recurring'
}

/** 未知の値(古いキャッシュ・手で入れた行)を弾いて感情スタンプとして読む */
export function isSatisfaction(value: unknown): value is Satisfaction {
  return typeof value === 'string' && (SATISFACTION_VALUES as readonly string[]).includes(value)
}

/** 感情スタンプ。未設定・未知の値はすべて null に寄せる */
export function satisfactionOf(t: Transaction): Satisfaction | null {
  return isSatisfaction(t.satisfaction) ? t.satisfaction : null
}

/**
 * 自分の実質支出(彼女の負担分を除く)。
 *
 * 「誰が払ったか」(機能018 の partner_paid)では変わらない。ここが表しているのは
 * *誰がいくら消費したか* であって、財布から出た現金の動きではないため。
 * 立て替えの向きは預かり残高(partnerBalance.ts)だけが引き受ける。
 * 預かり・返金・調整は支出ではないので 0。
 *
 * おごり・値引き (favors.ts) でも変わらない。浮いた分は払っていないお金なので、
 * ここに足すと支出の合計・ペース・予算のすべてに嘘が乗る。
 * 全額おごってもらった回は amount が 0 で、この関数も 0 を返す(それが正しい)。
 */
export function ownAmount(t: Transaction): number {
  return t.type === 'expense' ? t.amount - t.partner_amount : 0
}
