export type TransactionType = 'expense' | 'partner_deposit'

export interface Transaction {
  id: string
  date: string // YYYY-MM-DD
  type: TransactionType
  amount: number // 支払い総額(円)。partner_deposit の場合は預かり額
  category: string | null
  memo: string
  store: string // お店(店名)。任意。支出でのみ使用(既定は空文字)
  partner_amount: number // 支出のうち彼女の負担分(円)。彼女残高から差し引かれる
  created_at: string
  // 'recurring' なら繰り返し入力が自動生成した行。手入力の行には無い(列自体が
  // 無い環境もあるので任意)。編集・削除の扱いは手入力の行と同じ。
  source?: string | null
}

/** 繰り返し入力によって自動生成された行か */
export function isAutoGenerated(t: Transaction): boolean {
  return t.source === 'recurring'
}

// 自分の実質支出(彼女の負担分を除く)
export function ownAmount(t: Transaction): number {
  return t.type === 'expense' ? t.amount - t.partner_amount : 0
}
