// ============================================================
// 履歴の1行 (機能146 スワイプ / 149 長押し / 151 複数選択)
//
// 判定そのものは lib/rowGesture.ts の純粋関数に任せ、
// ここは「イベントを渡して、返ってきた判定どおりに描く」だけにしている。
// 優先順位(選択モード > 縦スクロール > スワイプ > 長押し > タップ)も
// すべて rowGesture.ts のコメントに書いてある。
// ============================================================

import { useEffect, useRef, useState } from 'react'
import type { PointerEvent as ReactPointerEvent } from 'react'
import type { Transaction } from '../lib/types'
import { isAutoGenerated, ownAmount, partnerPaid, tagsOf } from '../lib/types'
import { ledgerRowTitle, partnerImpact } from '../lib/partnerBalance'
import { formatDate, yen } from '../lib/format'
import { categoryLabel, resolveCategoryVisual } from '../lib/categories'
import { CategoryVisualBadge } from './categoryIcons'
import { IconEdit, IconTrash } from './historyIcons'
import {
  LONG_PRESS_MS,
  committedAction,
  nextPhase,
  shouldFireTap,
  swipeVisual,
  type RowGesturePhase,
} from '../lib/rowGesture'

interface Props {
  tx: Transaction
  /** 検索結果など、月をまたいで並ぶ一覧では日付も出す */
  showDate?: boolean
  selectMode: boolean
  picked: boolean
  /** タップ / 右スワイプ: 編集シートを開く */
  onOpen: (t: Transaction) => void
  onLongPress: (t: Transaction) => void
  /** 左スワイプ: 削除(取り消しバーが出る) */
  onSwipeDelete: (t: Transaction) => void
  onTogglePick: (t: Transaction) => void
}

export default function HistoryTxRow({
  tx,
  showDate = false,
  selectMode,
  picked,
  onOpen,
  onLongPress,
  onSwipeDelete,
  onTogglePick,
}: Props) {
  const [dx, setDx] = useState(0)
  const [settling, setSettling] = useState(false)
  const phaseRef = useRef<RowGesturePhase>('pending')
  const startRef = useRef({ x: 0, y: 0, t: 0 })
  const pointerRef = useRef<number | null>(null)
  const timerRef = useRef<number | null>(null)

  const clearTimer = () => {
    if (timerRef.current !== null) {
      window.clearTimeout(timerRef.current)
      timerRef.current = null
    }
  }

  // 画面から消えるときにタイマーを残さない(消えた行のメニューが後から出ないように)
  useEffect(() => clearTimer, [])

  // 選択モードに入ったら、引きかけの行は元に戻す(モードが最優先)
  useEffect(() => {
    if (selectMode) {
      clearTimer()
      pointerRef.current = null
      setDx(0)
    }
  }, [selectMode])

  const handlePointerDown = (e: ReactPointerEvent<HTMLDivElement>) => {
    if (selectMode) return // 0. 選択中はスワイプも長押しもしない
    if (e.pointerType === 'mouse' && e.button !== 0) return
    if (pointerRef.current !== null) {
      // 2本目の指(ピンチ等)— この操作は何も起こさない
      phaseRef.current = 'scroll'
      return
    }
    pointerRef.current = e.pointerId
    startRef.current = { x: e.clientX, y: e.clientY, t: e.timeStamp }
    phaseRef.current = 'pending'
    setSettling(false)
    timerRef.current = window.setTimeout(() => {
      // 動かさずに押し続けていたときだけメニューを出す
      if (phaseRef.current !== 'pending') return
      phaseRef.current = 'longpress'
      navigator.vibrate?.(10) // 対応端末だけ。反応した合図
      onLongPress(tx)
    }, LONG_PRESS_MS)
  }

  const handlePointerMove = (e: ReactPointerEvent<HTMLDivElement>) => {
    if (pointerRef.current !== e.pointerId) return
    const moveX = e.clientX - startRef.current.x
    const moveY = e.clientY - startRef.current.y
    const phase = nextPhase(phaseRef.current, moveX, moveY, e.timeStamp - startRef.current.t)
    phaseRef.current = phase
    if (phase !== 'pending') clearTimer()
    if (phase === 'swipe') setDx(moveX)
  }

  const handlePointerUp = (e: ReactPointerEvent<HTMLDivElement>) => {
    if (pointerRef.current !== e.pointerId) return
    clearTimer()
    pointerRef.current = null
    if (phaseRef.current !== 'swipe') return
    const action = committedAction(e.clientX - startRef.current.x)
    setSettling(true)
    setDx(0)
    if (action === 'delete') onSwipeDelete(tx)
    else if (action === 'edit') onOpen(tx)
  }

  const handlePointerCancel = () => {
    // 縦スクロールが始まるとブラウザが cancel を投げる。何も起こさず戻す
    clearTimer()
    pointerRef.current = null
    if (phaseRef.current === 'pending') phaseRef.current = 'scroll'
    setSettling(true)
    setDx(0)
  }

  const handleClick = () => {
    if (selectMode) {
      onTogglePick(tx)
      return
    }
    // スワイプ・スクロール・長押しのあとはタップとして扱わない
    if (!shouldFireTap(phaseRef.current)) return
    onOpen(tx)
  }

  const visual = swipeVisual(dx)
  const rowClass = [
    'hist-row',
    visual.armed && visual.action === 'delete' ? 'is-armed-delete' : '',
    visual.armed && visual.action === 'edit' ? 'is-armed-edit' : '',
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div
      className={rowClass}
      onPointerDown={handlePointerDown}
      onPointerMove={handlePointerMove}
      onPointerUp={handlePointerUp}
      onPointerCancel={handlePointerCancel}
      // 長押し中に iOS の選択メニュー・右クリックメニューを出さない
      onContextMenu={(e) => e.preventDefault()}
    >
      {visual.revealed && visual.action !== null && (
        <div className="hist-row-back" aria-hidden="true">
          {visual.action === 'edit' ? (
            <span className="hist-back-edit">
              <IconEdit /> {visual.armed ? '離すと編集' : '編集'}
            </span>
          ) : (
            <span className="hist-back-delete">
              <IconTrash /> {visual.armed ? '離すと削除' : '削除'}
            </span>
          )}
        </div>
      )}
      <div
        className={`hist-row-front${settling ? ' is-settling' : ''}`}
        style={{ transform: `translateX(${visual.offset}px)` }}
      >
        <RowBody
          tx={tx}
          showDate={showDate}
          selectMode={selectMode}
          picked={picked}
          onClick={handleClick}
        />
      </div>
    </div>
  )
}

function RowBody({
  tx,
  showDate,
  selectMode,
  picked,
  onClick,
}: {
  tx: Transaction
  showDate: boolean
  selectMode: boolean
  picked: boolean
  onClick: () => void
}) {
  // 支出以外(預かり・返金・調整)は財布のアイコンと専用の見出しで出す。
  // 金額も「残高への影響額」で出さないと、返金・調整の行が ¥0 に見えてしまう
  const isExpense = tx.type === 'expense'
  const impact = partnerImpact(tx)
  const visual = isExpense
    ? resolveCategoryVisual(tx.category)
    : ({ kind: 'icon', icon: 'wallet' } as const)
  // タイトルの優先順位: お店 → メモ → カテゴリ名(従来どおり)
  const title = isExpense ? tx.store || tx.memo || categoryLabel(tx.category) : ledgerRowTitle(tx)

  const subParts: string[] = []
  // 検索結果は月をまたぐので、どの日の記録か分かるよう先頭に日付を出す
  if (showDate) subParts.push(formatDate(tx.date))
  if (!isExpense) {
    if (tx.memo) subParts.push(tx.memo)
  } else {
    if (tx.store && tx.memo) subParts.push(tx.memo)
    if (tx.store || tx.memo) subParts.push(categoryLabel(tx.category))
    if (tx.partner_amount > 0) subParts.push(`うち彼女分 ${yen(tx.partner_amount)}`)
    // 機能018: 彼女が払った回。書かないと「実質支出」との差が読めない
    if (partnerPaid(tx) > 0) subParts.push(`彼女が ${yen(partnerPaid(tx))} 支払い`)
  }
  // 機能088: タグは末尾に。付いていない記録の見え方は今までと変わらない
  for (const tag of tagsOf(tx)) subParts.push(`#${tag}`)
  if (isAutoGenerated(tx)) subParts.push('自動生成')

  return (
    <button
      className={`tx-row${picked ? ' is-picked' : ''}`}
      onClick={onClick}
      aria-pressed={selectMode ? picked : undefined}
      aria-label={selectMode ? `${title} を選ぶ` : undefined}
    >
      {selectMode ? (
        <span className={`hist-check${picked ? ' is-on' : ''}`} aria-hidden="true">
          {picked ? '✓' : ''}
        </span>
      ) : (
        <CategoryVisualBadge visual={visual} size={34} />
      )}
      <span className="tx-body">
        <span className="tx-title" style={{ display: 'block' }}>
          {title}
        </span>
        {subParts.length > 0 && (
          <span className="tx-sub hist-row-date" style={{ display: 'block' }}>
            {subParts.join(' ・ ')}
          </span>
        )}
      </span>
      <span className={`tx-amount ${!isExpense && impact > 0 ? 'positive' : ''}`}>
        {isExpense
          ? `-${yen(ownAmount(tx))}`
          : impact > 0
            ? `+${yen(impact)}`
            : `-${yen(-impact)}`}
      </span>
    </button>
  )
}
