import { useEffect, useRef, useState, type ReactNode } from 'react'
import type { SupabaseClient } from '@supabase/supabase-js'
import { useTransactions } from '../hooks/useTransactions'
import { signOutByUser } from '../lib/supabaseClient'
import { categoryLabel, initCategories } from '../lib/categories'
import { sendDueMonthlySummaries } from '../lib/monthlySummary'
import { isAutoGenerated, type Satisfaction, type Transaction } from '../lib/types'
import { initStoreCategories } from '../lib/storeCategories'
import { generateDueTransactions, initRecurringRules } from '../lib/recurringRules'
import { initTransactionTemplates, isTemplatesUnavailable } from '../lib/transactionTemplates'
import { initSatisfaction } from '../lib/satisfaction'
import { initAssets, isAssetsTabVisible, useAssetsStore } from '../lib/assets'
import { initDiscordWebhook } from '../lib/discordWebhook'
import { todayISO } from '../lib/format'
import { withSatisfaction } from '../lib/txActions'
import { amountMaskToggleLabel, toggleAmountMask, useAmountMasked } from '../lib/amountMask'
import { type Guidance } from '../lib/errorGuidance'
import InputTab from './InputTab'
import HistoryTab from './HistoryTab'
import ReportTab from './ReportTab'
import PartnerTab from './PartnerTab'
import AssetsTab from './AssetsTab'
import TransactionForm, { type DatePrefill } from './TransactionForm'
import SettingsSheet from './SettingsSheet'
import QuarantineSheet from './QuarantineSheet'
import TemplateSaveSheet from './TemplateSaveSheet'
import { IconCalendar, IconChart, IconGear, IconHeart, IconLogout, IconPen } from './icons'
import { IconAssets } from './assetIcons'
import { IconEye, IconEyeOff } from './maskIcons'
import useBodyScrollLock from '../hooks/useBodyScrollLock'
import '../offline.css'
import '../settings.css'

type Tab = 'input' | 'history' | 'report' | 'partner' | 'assets'

/**
 * エラーの「原因」と「次の行動」を出す (機能161)。
 *
 * 原文だけを出していた頃は、読んでも次に何をすればいいのか分からなかった。
 * 原因を1行、やることを箇条書き、原文は最後に小さく — の順に固定している
 * (原文が先頭にあると、読む気を失ってやることまで届かない)。
 */
function ErrorGuide({ guide, onOpenSettings }: { guide: Guidance; onOpenSettings: () => void }) {
  return (
    <>
      <span className="err-guide-summary">{guide.summary}</span>
      <ul className="err-guide-actions">
        {guide.actions.map((a) => (
          <li key={a}>{a}</li>
        ))}
      </ul>
      {/* 接続設定が疑わしいときだけ、その場からやり直せる場所へ連れて行く */}
      {guide.kind === 'connection' && (
        <button type="button" className="btn-ghost err-guide-btn" onClick={onOpenSettings}>
          接続設定を確認する
        </button>
      )}
      {guide.detail && <span className="err-guide-detail">詳細: {guide.detail}</span>}
    </>
  )
}

const TABS: { id: Tab; label: string; icon: ReactNode }[] = [
  { id: 'input', label: '入力', icon: <IconPen /> },
  { id: 'history', label: '履歴', icon: <IconCalendar /> },
  { id: 'report', label: 'レポート', icon: <IconChart /> },
  { id: 'partner', label: '彼女', icon: <IconHeart /> },
]

// 資産タブ (機能101) は既存4タブの位置を動かさないよう末尾に足す。
// migration-assets.sql 未実行のときは配列ごと出さない
const ASSETS_TAB = { id: 'assets' as const, label: '資産', icon: <IconAssets /> }

export default function MainScreen({ supabase }: { supabase: SupabaseClient }) {
  const store = useTransactions(supabase)
  const [tab, setTab] = useState<Tab>('input')
  const [editing, setEditing] = useState<Transaction | null>(null)
  const [showSettings, setShowSettings] = useState(false)
  // 同期できずに隔離された記録の一覧 (設定からも、下のバナーからも開ける)
  const [showQuarantine, setShowQuarantine] = useState(false)
  const [templateFrom, setTemplateFrom] = useState<Transaction | null>(null)
  // 履歴カレンダーの「この日で入力する」で入力タブへ渡す日付(機能053)
  const [datePrefill, setDatePrefill] = useState<DatePrefill | undefined>(undefined)

  // 取引編集モーダルを開いている間は背面ページを固定する
  // (設定/Geminiキーの各シートは自前でロックを取得する)
  useBodyScrollLock(editing !== null)

  // カテゴリをSupabaseから読み込む(初回は既定カテゴリを移行)。失敗時はキャッシュで継続
  useEffect(() => {
    void initCategories(supabase)
  }, [supabase])

  // 後から足したマスタデータ。いずれもテーブルが無ければ静かに無効化されるので、
  // マイグレーション未実行でも記録・入力には影響しない
  useEffect(() => {
    void initStoreCategories(supabase)
    void initTransactionTemplates(supabase)
    // 感情スタンプの列があるか(migration-satisfaction.sql の実行有無)も同じ扱い
    void initSatisfaction(supabase)
    // 資産・純資産 (機能101)。テーブルが無ければ資産タブを出さないだけ
    void initAssets(supabase)
    // Discord の Webhook URL。他の端末で設定・解除した内容をここで取り込み、
    // この端末にしか無かった URL はここでサーバーへ引き上げる。
    // テーブルが無い/通信できないときはキャッシュに触らないので、
    // **通知はどの場合でも従来どおり飛び続ける**(discordWebhook.ts を参照)
    void initDiscordWebhook(supabase)
  }, [supabase])

  // 感情スタンプの付け直し(機能143)。編集と同じ update 経路なので
  // オフラインでもキューに積まれ、記録が失われることはない。
  //
  // 内容は必ず withSatisfaction(= transactionToInput が写した「その行が持っている
  // 事実」に気分だけを乗せたもの)から作る。項目を手書きしていた頃は partner_paid が
  // 抜けており、サーバーのデータは部分更新なので無事だったが、通知の差分計算が
  // それを 0 とみなして「記録が修正されました 差分 −¥5,000」という
  // 実在しない差分を彼女に送っていた(組み立てと理由は lib/txActions.ts)。
  const setSatisfaction = async (t: Transaction, value: Satisfaction) => {
    await store.update(t.id, withSatisfaction(t, value))
  }

  // 履歴のカレンダーで選んだ日付をそのまま入力タブへ持っていく(機能053)
  const startInputOn = (date: string) => {
    setDatePrefill({ nonce: (datePrefill?.nonce ?? 0) + 1, date })
    setTab('input')
  }

  // 繰り返し入力の未生成分は「アプリを開いたとき」にまとめて作る(サーバー側の cron が無いため)。
  // store.add はオフラインキュー経由なので、生成した記録が失われることはない
  useEffect(() => {
    void initRecurringRules(supabase).then(() =>
      generateDueTransactions(supabase, todayISO(), store.add)
    )
    // 起動時に1回だけ実行する(store.add は毎描画で作り直されるため依存に含めない)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [supabase])

  // 月末の預かり金サマリー (機能016)。こちらもサーバー側の cron が無いので、
  // 取引の読み込みが済んだあとに「まだ送っていない月」をまとめて送る。
  // 同じ月を二度送らないことは Supabase 側の一意制約で保証している
  // (monthlySummary.ts のコメントを参照)。この端末で1回だけ試みる。
  const summaryTriedRef = useRef(false)
  useEffect(() => {
    if (summaryTriedRef.current || store.loading) return
    summaryTriedRef.current = true
    // 投げっぱなし。失敗しても記録・同期には一切影響しない
    void sendDueMonthlySummaries(supabase, store.transactions, todayISO(), categoryLabel)
  }, [supabase, store.loading, store.transactions])

  // オンラインなのに同期が詰まっている(= 記録は保持されているが送れていない)状態。
  // 放置すると「履歴に反映されない」ように見えるので、対処法とあわせて明示する
  const stalled =
    store.isOnline && store.pendingCount > 0 && !store.syncing && store.errorGuide !== null

  // エラーの原因と次の行動 (機能161)。
  // フックが構造のまま (Guidance) 渡してくるので、ここでは分類し直さない。
  // 以前は畳んだ文字列から引き直していたが、フック側も errorGuidance を通すように
  // なったため、そのままだと「畳んだ案内」をもう一度案内で包むことになる
  const guide = store.errorGuide

  // 金額の目隠し (機能169)。
  // 整形関数 (format.ts の yen など) は React の外にある状態を読むので、
  // 切り替えても自動では描き直されない。アプリの全画面がこの下にぶら下がっているため、
  // ここで購読しておけば1回の再描画で画面じゅうの金額が伏字に切り替わる。
  const masked = useAmountMasked()

  // 資産タブの有無 (機能101)。テーブルが無いと分かった時点で選択中でも入力タブへ戻す
  const assetsStore = useAssetsStore()
  const assetsVisible = isAssetsTabVisible(assetsStore)
  const tabs = assetsVisible ? [...TABS, ASSETS_TAB] : TABS
  const activeTab: Tab = tab === 'assets' && !assetsVisible ? 'input' : tab

  return (
    <>
      <header className="app-header">
        <h1>家計簿</h1>
        <div className="header-actions">
          {/* 金額の目隠し (機能169)。
              人が近づいてから設定を開いていては間に合わないので、常に見えている
              ヘッダーに置く。誤操作したくないログアウトの隣にはしたくないため、
              歯車より左(タブから最も遠い側)に並べている */}
          <button
            className={`icon-btn${masked ? ' masked-on' : ''}`}
            aria-label={amountMaskToggleLabel(masked)}
            title={amountMaskToggleLabel(masked)}
            aria-pressed={masked}
            onClick={() => toggleAmountMask()}
          >
            {masked ? <IconEyeOff /> : <IconEye />}
          </button>
          <button
            className="icon-btn"
            aria-label="設定"
            onClick={() => setShowSettings(true)}
          >
            <IconGear />
          </button>
          <button
            className="icon-btn"
            aria-label="ログアウト"
            onClick={() => void signOutByUser(supabase)}
          >
            <IconLogout />
          </button>
        </div>
      </header>
      {!store.isOnline ? (
        <div className="sync-banner offline">
          オフライン — 記録は保存され、通信回復時に自動同期されます
          {store.pendingCount > 0 && `(保留 ${store.pendingCount}件)`}
        </div>
      ) : store.pendingCount > 0 && store.syncing ? (
        <div className="sync-banner syncing">同期中… ({store.pendingCount}件)</div>
      ) : stalled && guide ? (
        <div className="sync-banner warning">
          ⚠ 未同期の記録が {store.pendingCount}件あります
          <span className="banner-detail">
            <ErrorGuide guide={guide} onOpenSettings={() => setShowSettings(true)} />
          </span>
        </div>
      ) : null}
      {/* サーバーに断られて端末に取り置いた記録 (A/B)。
          再読み込みしても消えないよう、状態(localStorage)から直接出す。
          以前はエラー文言だけが頼りで、更新のたびに消えて痕跡がゼロになっていた */}
      {store.quarantined.length > 0 && (
        <div className="sync-banner warning">
          ⚠ 同期できなかった記録が {store.quarantined.length}件あります(この端末に残しています)
          <button
            type="button"
            className="btn-ghost banner-link"
            onClick={() => setShowQuarantine(true)}
          >
            中身を確認する
          </button>
        </div>
      )}
      <main className="app-main">
        {/* 未同期バナーに同じ内容を出しているときは重複表示しない */}
        {guide && !stalled && (
          <div className="error-text err-guide">
            <ErrorGuide guide={guide} onOpenSettings={() => setShowSettings(true)} />
          </div>
        )}
        {activeTab === 'input' && (
          <InputTab store={store} supabase={supabase} datePrefill={datePrefill} />
        )}
        {activeTab === 'history' && (
          <HistoryTab store={store} onEdit={setEditing} onStartInput={startInputOn} />
        )}
        {activeTab === 'report' && (
          <ReportTab
            transactions={store.transactions}
            onSetSatisfaction={setSatisfaction}
            /* 「回ごと」から過去の旅行にまとめてタグを付ける。
               書き込みは必ずオフラインキュー経由(updateMany)にする */
            onBulkUpdate={(updates) => void store.updateMany(updates)}
          />
        )}
        {activeTab === 'partner' && (
          <PartnerTab store={store} supabase={supabase} onEdit={setEditing} />
        )}
        {activeTab === 'assets' && <AssetsTab supabase={supabase} />}
      </main>
      <nav className="tab-bar">
        {tabs.map((t) => (
          <button
            key={t.id}
            className={activeTab === t.id ? 'active' : ''}
            onClick={() => setTab(t.id)}
          >
            <span className="tab-icon">{t.icon}</span>
            {t.label}
          </button>
        ))}
      </nav>
      {showSettings && (
        <SettingsSheet
          supabase={supabase}
          onClose={() => setShowSettings(false)}
          // CSV 書き出し (機能198)。未同期の記録も含んだ表示中の全件を渡す —
          // バックアップなので「まだサーバーに届いていない分」こそ落としてはいけない
          transactions={store.transactions}
          quarantinedCount={store.quarantined.length}
          onOpenQuarantine={() => {
            setShowSettings(false)
            setShowQuarantine(true)
          }}
        />
      )}
      {showQuarantine && (
        <QuarantineSheet
          entries={store.quarantined}
          onRetry={(id) => void store.retryQuarantined(id)}
          onDiscard={(id) => store.discardQuarantined(id)}
          onClose={() => setShowQuarantine(false)}
        />
      )}
      {editing && (
        <div className="modal-backdrop" onClick={() => setEditing(null)}>
          <div className="modal-sheet" onClick={(e) => e.stopPropagation()}>
            <div className="sheet-header">
              <h2>{editing.type === 'expense' ? '支出を編集' : '預かりを編集'}</h2>
              <button className="btn-ghost" onClick={() => setEditing(null)}>
                閉じる
              </button>
            </div>
            {isAutoGenerated(editing) && (
              <p className="muted auto-generated-note">
                繰り返し入力から自動生成された記録です(編集・削除できます)
              </p>
            )}
            <TransactionForm
              initial={editing}
              submitLabel="更新する"
              // 編集シートでも「そのカテゴリで使ったお店」「過去のタグ」を候補に出す
              // (入力タブと同じ操作でお店を選び直せるようにするため)
              knownTransactions={store.transactions}
              onSubmit={async (input) => {
                await store.update(editing.id, input)
                setEditing(null)
              }}
              // 削除前の確認は出さない。消したあとに出る「元に戻す」バーが
              // 同じ役割を果たすので、摩擦は操作の前ではなく後ろに置く
              onDelete={async () => {
                await store.remove(editing.id)
                setEditing(null)
              }}
            />
            {editing.type === 'expense' && !isTemplatesUnavailable() && (
              <button className="btn-ghost template-from-tx" onClick={() => setTemplateFrom(editing)}>
                これをテンプレートにする
              </button>
            )}
          </div>
        </div>
      )}
      {templateFrom && (
        <TemplateSaveSheet
          supabase={supabase}
          transaction={templateFrom}
          onSaved={() => setTemplateFrom(null)}
          onClose={() => setTemplateFrom(null)}
        />
      )}
    </>
  )
}
